### ISSUE TITLE
Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.notebook-search.v1" is invalid: data: Too long: must have at most 1048576 bytes

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/notebook-search-helm-charts#1]
Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.notebook-search.v1" is invalid: data: Too long: must have at most 1048576 bytes

**Comment by skoulouzis** [comment]
Looks like the values:
```yaml
global:
  postgresql:
    auth:
      username: "postgres"
      database: "notebooksearch"
```
were creating this problem.
